pref("extensions.tabutils@ithinc.cn.description", "chrome://tabutils/locale/tabutils.properties");

pref("extensions.tabutils.openBookmarksInTab", true);
pref("extensions.tabutils.openHomepageInTab", true);
pref("extensions.tabutils.openUrlInTab", true);
pref("extensions.tabutils.openInternalInCurrent", false);
pref("extensions.tabutils.loadHomepageInBackground", false);
pref("extensions.tabutils.loadUrlInBackground", false);
pref("extensions.tabutils.loadSearchInBackground", false);
pref("extensions.tabutils.loadNewInBackground", false);
pref("extensions.tabutils.loadDuplicateInBackground", false);
pref("extensions.tabutils.loadForeignInBackground", false);
pref("extensions.tabutils.loadAllInBackground", false);
pref("extensions.tabutils.loadAllInForeground", false);
pref("extensions.tabutils.openTabNext", 3);
pref("extensions.tabutils.openTabNext.keepOrder", true);
pref("extensions.tabutils.openDuplicateNext", true);
pref("extensions.tabutils.restoreOriginalPosition", true);
pref("extensions.tabutils.reuseBlank", 0);
pref("extensions.tabutils.loadInNewTab", 2);
pref("extensions.tabutils.markNewAsBlank", false);

pref("extensions.tabutils.selectOnClose", 74);
pref("extensions.tabutils.removeUnintentionalBlank", false);
pref("extensions.tabutils.closeLastWindowWithLastTab", false);
pref("extensions.tabutils.handleCtrlTab", false);
pref("extensions.tabutils.handleCtrlArrow", false);
pref("extensions.tabutils.handleCtrl", true);

pref("extensions.tabutils.singleWindowMode", false);
pref("extensions.tabutils.openLinkInTab", false);
pref("extensions.tabutils.openExternalInTab", false);
pref("extensions.tabutils.openLinkWithHistory", false);

pref("extensions.tabutils.middleClickBookmarks", 2);
pref("extensions.tabutils.rightClickBookmarks", 0);
pref("extensions.tabutils.ctrlClickBookmarks", 1);
pref("extensions.tabutils.shiftClickBookmarks", 0);
pref("extensions.tabutils.middleClickLinks", 0);
pref("extensions.tabutils.rightClickLinks", 0);
pref("extensions.tabutils.ctrlClickLinks", 0);
pref("extensions.tabutils.shiftClickLinks", 0);

pref("extensions.tabutils.leftClickTab", 0);
pref("extensions.tabutils.leftClickTabDelay", 250);
pref("extensions.tabutils.middleClickTab", 4);
pref("extensions.tabutils.rightClickTab", 0);
pref("extensions.tabutils.dblClickTab", 4);
pref("extensions.tabutils.ctrlClickTab", 0);
pref("extensions.tabutils.altClickTab", 0);
pref("extensions.tabutils.shiftClickTab", 0);
pref("extensions.tabutils.ctrlShiftClickTab", 0);

pref("extensions.tabutils.leftClickTabBar", 0);
pref("extensions.tabutils.middleClickTabBar", 5);
pref("extensions.tabutils.rightClickTabBar", 0);
pref("extensions.tabutils.dblClickTabBar", 0);
pref("extensions.tabutils.ctrlClickTabBar", 0);
pref("extensions.tabutils.altClickTabBar", 0);
pref("extensions.tabutils.shiftClickTabBar", 0);

pref("extensions.tabutils.middleClickNewTabButton", 0);
pref("extensions.tabutils.rightClickNewTabButton", 15);
pref("extensions.tabutils.ctrlClickNewTabButton", 0);
pref("extensions.tabutils.altClickNewTabButton", 0);
pref("extensions.tabutils.shiftClickNewTabButton", 0);

pref("extensions.tabutils.mouse.100.label", "");
pref("extensions.tabutils.mouse.100.oncommand", "");

pref("extensions.tabutils.dragAndGo", false);
pref("extensions.tabutils.mouseReleaseSelect", false);
pref("extensions.tabutils.mouseHoverPreview", true);
pref("extensions.tabutils.mouseHoverPreviewDelay", 250);
pref("extensions.tabutils.mouseHoverSelect", false);
pref("extensions.tabutils.mouseHoverSelectDelay", 0);
pref("extensions.tabutils.mouseHoverLoad", true);
pref("extensions.tabutils.mouseHoverLoadDelay", 1500);
pref("extensions.tabutils.mouseScrollSelect", false);
pref("extensions.tabutils.mouseScrollSelectDir", false);
pref("extensions.tabutils.mouseScrollSelectWrap", false);

pref("extensions.tabutils.tabBarPosition", 0);
pref("extensions.tabutils.closeButtons", 1);
pref("extensions.tabutils.showTabCounter", false);
pref("extensions.tabutils.showLeftSpace", false);
pref("extensions.tabutils.showRightSpace", false);
pref("extensions.tabutils.showAllTabs", false);
pref("extensions.tabutils.highlightCurrent", false);
pref("extensions.tabutils.highlightUnread", false);
pref("extensions.tabutils.highlightRead", false);
pref("extensions.tabutils.highlightUnloaded", true);
pref("extensions.tabutils.highlightSelected", true);
pref("extensions.tabutils.styles.current", '{"bold":true,"color":true,"colorCode":"blue"}');
pref("extensions.tabutils.styles.unread", '{"italic":true,"color":true,"colorCode":"red"}');
pref("extensions.tabutils.styles.read", "");
pref("extensions.tabutils.styles.unloaded", '{"opacity":true,"opacityCode":0.5}');
pref("extensions.tabutils.styles.selected", '{"color":true,"colorCode":"highlighttext","bgColor":true,"bgColorCode":"highlight"}');
pref("extensions.tabutils.selector.current", '[selected]');
pref("extensions.tabutils.selector.unread", '[unread]:not([selected])');
pref("extensions.tabutils.selector.read", ':not([unread]):not([selected])');
pref("extensions.tabutils.selector.unloaded", '[pending]');
pref("extensions.tabutils.selector.selected", '[multiselected]');

pref("extensions.tabutils.statusbarMode", 0);
pref("extensions.tabutils.hideOpenInTab", false);
pref("extensions.tabutils.hideLoadInBackground", false);
pref("extensions.tabutils.hideLoadInForeground", true);

pref("extensions.tabutils.menu.menu_tuOptions", true);
pref("extensions.tabutils.menu.context_newTab", true);
pref("extensions.tabutils.menu.context_duplicateTab", true);
pref("extensions.tabutils.menu.context_reloadEvery", false);
pref("extensions.tabutils.menu.context_openTabInWindow", false);
pref("extensions.tabutils.menu.context_moveToWindow", false);
pref("extensions.tabutils.menu.context_mergeWindow", false);
pref("extensions.tabutils.menu.context_tabViewMenu", true);
pref("extensions.tabutils.menu.context_mergeGroup", false);
pref("extensions.tabutils.menu.context_recentlyClosedTabs", true);
pref("extensions.tabutils.menu.context_readTab", false);
pref("extensions.tabutils.menu.context_protectTab", false);
pref("extensions.tabutils.menu.context_lockTab", false);
pref("extensions.tabutils.menu.context_faviconizeTab", false);
pref("extensions.tabutils.menu.context_renameTab", false);
pref("extensions.tabutils.menu.context_restartTab", false);
pref("extensions.tabutils.menu.context_closeLeftTabs", false);
pref("extensions.tabutils.menu.context_closeRightTabs", false);
pref("extensions.tabutils.menu.context_closeTabsToTheEnd", false);
pref("extensions.tabutils.menu.context_closeOtherTabs", true);
pref("extensions.tabutils.menu.context_closeOtherTabs.insertafter", "context_closeRightTabs");
pref("extensions.tabutils.menu.context_closeDuplicateTabs", false);
pref("extensions.tabutils.menu.context_closeSimilarTabs", false);
pref("extensions.tabutils.menu.context_markTab", false);
pref("extensions.tabutils.menu.context_markTabs", false);
pref("extensions.tabutils.menu.context_selectTabs", false);
pref("extensions.tabutils.menu.context_selectSimilarTabs", false);
pref("extensions.tabutils.menu.context_selectAllTabs", false);
pref("extensions.tabutils.menu.context_unselectAllTabs", false);
pref("extensions.tabutils.menu.context_invertSelection", false);
pref("extensions.tabutils.menu.context_showAllTabs", false);
pref("extensions.tabutils.menu.context_readAllTabs", false);
pref("extensions.tabutils.menu.context_protectAllTabs", false);
pref("extensions.tabutils.menu.context_lockAllTabs", false);
pref("extensions.tabutils.menu.context_faviconizeAllTabs", false);
pref("extensions.tabutils.menu.context_restartAllTabs", false);
pref("extensions.tabutils.menu.context_closeAllTabs", false);
pref("extensions.tabutils.menu.context_closeAllDuplicateTabs", false);

pref("extensions.tabutils.menu.context_copyTabURL", false);
pref("extensions.tabutils.menu.context_copyTabURL.label", "Copy Tab URL");
pref("extensions.tabutils.menu.context_copyTabURL.accesskey", "U");
pref("extensions.tabutils.menu.context_copyTabURL.multiselected", "any");
pref("extensions.tabutils.menu.context_copyTabURL.oncommand", "Cc['@mozilla.org/widget/clipboardhelper;1'].getService(Ci.nsIClipboardHelper).copyString([tab.linkedBrowser.currentURI.spec for (tab of gBrowser.mContextTabs)].join('\\n'));");

pref("extensions.tabutils.menu.context_template", false);
pref("extensions.tabutils.menu.context_template.label", "");
pref("extensions.tabutils.menu.context_template.accesskey", "");
pref("extensions.tabutils.menu.context_template.insertbefore", "");
pref("extensions.tabutils.menu.context_template.multiselected", "");
pref("extensions.tabutils.menu.context_template.oncommand", "");

pref("extensions.tabutils.shortcut.tuKeyset.disabled", false);
pref("extensions.tabutils.shortcut.key_copyPageLocation", true);
pref("extensions.tabutils.shortcut.key_cutPageLocation", false);
pref("extensions.tabutils.shortcut.key_pasteAndGo", true);
pref("extensions.tabutils.shortcut.key_pasteAndSearch", true);
pref("extensions.tabutils.shortcut.key_undoCloseTab2", true);
pref("extensions.tabutils.shortcut.key_recentlyClosedTabs", true);
pref("extensions.tabutils.shortcut.key_duplicateTab", true);
pref("extensions.tabutils.shortcut.key_protectTab", true);
pref("extensions.tabutils.shortcut.key_lockTab", true);
pref("extensions.tabutils.shortcut.key_freezeTab", true);
pref("extensions.tabutils.shortcut.key_faviconizeTab", true);
pref("extensions.tabutils.shortcut.key_pinTab", true);
pref("extensions.tabutils.shortcut.key_closeLeftTabs", true);
pref("extensions.tabutils.shortcut.key_closeAllTabs", true);
pref("extensions.tabutils.shortcut.key_closeRightTabs", true);
pref("extensions.tabutils.shortcut.key_moveTabBackward", true);
pref("extensions.tabutils.shortcut.key_moveTabForward", true);
pref("extensions.tabutils.shortcut.key_moveTabToStart", true);
pref("extensions.tabutils.shortcut.key_moveTabToEnd", true);
pref("extensions.tabutils.shortcut.key_prevGroup", false);
pref("extensions.tabutils.shortcut.key_nextGroup", false);

pref("extensions.tabutils.shortcut.key_selectTab1.oncommand", "gBrowser.selectUnpinnedTabAtIndex(0, event);");
pref("extensions.tabutils.shortcut.key_selectTab2.oncommand", "gBrowser.selectUnpinnedTabAtIndex(1, event);");
pref("extensions.tabutils.shortcut.key_selectTab3.oncommand", "gBrowser.selectUnpinnedTabAtIndex(2, event);");
pref("extensions.tabutils.shortcut.key_selectTab4.oncommand", "gBrowser.selectUnpinnedTabAtIndex(3, event);");
pref("extensions.tabutils.shortcut.key_selectTab5.oncommand", "gBrowser.selectUnpinnedTabAtIndex(4, event);");
pref("extensions.tabutils.shortcut.key_selectTab6.oncommand", "gBrowser.selectUnpinnedTabAtIndex(5, event);");
pref("extensions.tabutils.shortcut.key_selectTab7.oncommand", "gBrowser.selectUnpinnedTabAtIndex(6, event);");
pref("extensions.tabutils.shortcut.key_selectTab8.oncommand", "gBrowser.selectUnpinnedTabAtIndex(7, event);");
pref("extensions.tabutils.shortcut.key_selectLastTab.oncommand", "gBrowser.selectUnpinnedTabAtIndex(-1, event);");

pref("extensions.tabutils.shortcut.key_template", false);
pref("extensions.tabutils.shortcut.key_template.key", "");
pref("extensions.tabutils.shortcut.key_template.keycode", "");
pref("extensions.tabutils.shortcut.key_template.modifiers", "");
pref("extensions.tabutils.shortcut.key_template.oncommand", "");

pref("extensions.tabutils.button.newtab-button.onclick", "gBrowser.onTabClick(event);");
pref("extensions.tabutils.button.alltabs-button.onclick", "");
pref("extensions.tabutils.button.tabs-closebutton.onclick", "");
pref("extensions.tabutils.button.undoclosetab-button.onclick", "");

pref("extensions.tabutils.button.button_template", false);
pref("extensions.tabutils.button.button_template.label", "");
pref("extensions.tabutils.button.button_template.image", "");
pref("extensions.tabutils.button.button_template.parent", "");
pref("extensions.tabutils.button.button_template.insertafter", "");
pref("extensions.tabutils.button.button_template.onclick", "");
pref("extensions.tabutils.button.button_template.oncommand", "");
pref("extensions.tabutils.button.button_template.tooltiptext", "");

pref("extensions.tabutils.css.example", "");
pref("extensions.tabutils.js.example", "");

pref("extensions.tabutils.disableTabMoveAnimation", true);
pref("extensions.tabutils.css.disableTabMoveAnimation", ".tabbrowser-tab[pinned] {-moz-transform: none !important;}");
pref("extensions.tabutils.css.fixTabViewButton", "window[OS='WINNT']:not([v29='true']) #tabview-button > toolbarbutton > .toolbarbutton-icon:not(:-moz-lwtheme) {list-style-image: url('chrome://browser/skin/tabview/tabview-inverted.png') !important;} /* Bug 748894 [Fx23] */");

pref("extensions.tabutils.invertAlt", true);
pref("extensions.tabutils.invertDrag", false);
pref("extensions.tabutils.centerCurrentTab", false);
pref("extensions.tabutils.delayResizing", true);
pref("extensions.tabutils.dragBindingAlive", true);
pref("extensions.tabutils.autoProtect", true);
pref("extensions.tabutils.autoLock", true);
pref("extensions.tabutils.autoFaviconize", true);
pref("extensions.tabutils.autoPin", true);
pref("extensions.tabutils.autoRename", true);
pref("extensions.tabutils.autoEnableAutoReload", true);
pref("extensions.tabutils.pinTab.autoProtect", false);
pref("extensions.tabutils.pinTab.autoLock", false);
pref("extensions.tabutils.pinTab.autoFaviconize", true);
pref("extensions.tabutils.pinTab.autoRevert", false);
pref("extensions.tabutils.pinTab.showPhantom", true);
pref("extensions.tabutils.tabFitTitle", false);
pref("extensions.tabutils.titleAsBookmark", false);
pref("extensions.tabutils.bookmarkWithHistory", false);
pref("extensions.tabutils.bookmarkAllWithHistory", true);
pref("extensions.tabutils.reloadInterval", 300);
pref("extensions.tabutils.restartAfter", 0);

//Tab Stack
pref("extensions.tabutils.autoStack", false);
pref("extensions.tabutils.autoExpandStackOnDragover", false);
pref("extensions.tabutils.autoExpandStackAndCollapseOthersOnSelect", true);
pref("extensions.tabutils.autoCollapseStackOnBlur", false);
pref("extensions.tabutils.autoCollapseNewStack", true);
pref("extensions.tabutils.dragToStack", false);
pref("extensions.tabutils.mouseHoverPopup", true);
pref("extensions.tabutils.mouseHoverPopupDelay", 750);

pref("extensions.tabutils.colorStack", true);
pref("extensions.tabutils.colorStack.0", "#50C2F8 20%");
pref("extensions.tabutils.colorStack.1", "#60FDC8 20%");
pref("extensions.tabutils.colorStack.2", "#67FF91 20%");
pref("extensions.tabutils.colorStack.3", "#81C3F8 20%");
pref("extensions.tabutils.colorStack.4", "#94B1FB 20%");
pref("extensions.tabutils.colorStack.5", "#ADEBE5 20%");
pref("extensions.tabutils.colorStack.6", "#AF9FF5 20%");
pref("extensions.tabutils.colorStack.7", "#BACEF8 20%");
pref("extensions.tabutils.colorStack.8", "#C9FF6F 20%");
pref("extensions.tabutils.colorStack.9", "#EAAEE6 20%");
pref("extensions.tabutils.colorStack.a", "#EACFA7 20%");
pref("extensions.tabutils.colorStack.b", "#F7A6B9 20%");
pref("extensions.tabutils.colorStack.c", "#F88371 20%");
pref("extensions.tabutils.colorStack.d", "#F8B7B3 20%");
pref("extensions.tabutils.colorStack.e", "#F8D7DA 20%");
pref("extensions.tabutils.colorStack.f", "#FFCF6E 20%");

pref("browser.tabs.tabMaxWidth", 250);
pref("browser.tabs.tabMinWidth", 100);
pref("browser.tabs.tabMinHeight", 20);
pref("network.dns.ignoreHostonly", false);
